name: blockchain_server
description: Blockchain server

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.0.0


dependencies:
  logging: ^1.2.0
  fixnum: ^1.1.0
  integral_isolates: ^0.5.1
  ribs_core: ^1.0.0-dev.11
  ribs_effect: ^1.0.0-dev.1
  grpc: ^3.2.4
  blockchain:
    path: ../blockchain
  blockchain_sdk:
    path: ../sdk
  blockchain_protobuf:
    path: ../protobuf_dart

dev_dependencies:
  test: ^1.25.0
