[package]
name = "giraffe_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
base58 = "0.2.0"
hex = "0.4.3"
prost = "0.13"
prost-types = "0.13"
sha256 = "1.5.0"

[build-dependencies]
prost-build = "0.13.3"
