name: blockchain_app
description: Blockchain App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  cryptography: ^2.5.0
  cryptography_flutter: ^2.3.0
  logging:
  fixnum:
  async:
  fpdart:
  rxdart:
  fast_base58: ^0.2.1
  integral_isolates: ^0.4.1
  flutter_background: ^1.2.0
  intl: ^0.18.1
  get_time_ago: ^1.2.5
  bit_array: ^2.2.0
  provider: ^6.0.5
  fluro: ^2.0.5
  blockchain:
    path: ../blockchain
  blockchain_codecs:
    path: ../codecs
  blockchain_common:
    path: ../common
  blockchain_crypto:
    path: ../crypto
  blockchain_protobuf:
    path: ../protobuf_dart
  blockchain_network:
    path: ../network
  blockchain_wallet:
    path: ../wallet
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
