name: blockchain_app
description: Blockchain App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  blockchain:
    path: ../blockchain
  blockchain_codecs:
    path: ../codecs
  blockchain_block_production:
    path: ../block_production
  blockchain_consensus:
    path: ../consensus
  blockchain_ledger:
    path: ../ledger
  blockchain_protobuf:
    path: ../protobuf_dart
  blockchain_common:
    path: ../common
  blockchain_network:
    path: ../network
  fixnum:
  ipsum:
  painter:
  fpdart:
  bit_array:
  async:
  graphview: ^1.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
