services:
  node:
    image: "seancheatham/blockchain-node:dev"
    pull_policy: "always"
    restart: "unless-stopped"
    ports:
      - "2023:2023"
    command:
      - "--genesis"
      - "https://github.com/SeanCheatham/blockchain/raw/genesis/b_9pGHV8YFQ7MDwXjBYD87bVky2LFHCwWecESaQ5K9nYKd.pbuf"
      - "--data-dir"
      - "/blockchain/data"
      - "--peer"
      - "134.122.14.213:2023"
    volumes:
      - "blockchain:/blockchain"
  envoy:
    build:
      context: envoy
      dockerfile: envoy.Dockerfile
    ports:
      - "2024:2024"
    links:
      - node
    volumes:
      - ./envoy/config.yaml:/etc/envoy/config.yaml

volumes:
  blockchain:
