name: giraffe_protocol
description: Giraffe blockchain protocol
publish_to: 'none'
version: 1.0.6

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.2"

dependencies:
  convert: ^3.1.1
  cryptography: ^2.5.0
  logging: ^1.2.0
  fixnum: ^1.1.0
  async: ^2.11.0
  fpdart: ^1.1.0
  rxdart: ^0.28.0
  fast_base58: ^0.2.1
  integral_isolates: ^0.5.1
  bit_array: ^2.2.0
  riverpod: ^2.5.1
  giraffe_sdk:
    path: ../sdk
  riverpod_annotation: ^2.3.5
  rational: ^2.2.3
  hashlib: ^1.19.2
  collection: ^1.18.0
  args: ^2.5.0
  quiver: ^3.2.2
  mutex: ^3.1.0
  async_queue: ^2.0.0
  rust_lib_giraffe_protocol:
    path: rust_builder
  flutter_rust_bridge: 2.5.0

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0
  custom_lint:
  analyzer: ^6.7.0
  mockito: ^5.4.4
  test: ^1.25.7
  integration_test:
    sdk: flutter
