name: blockchain_ledger
description: Blockchain Ledger

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.0.0


dependencies:
  fixnum:
  async: ^2.10.0
  rational: ^2.2.2
  fpdart: ^1.1.0
  hashlib: 
  logging:
  blockchain_protobuf:
    path: ../protobuf_dart
  blockchain_common:
    path: ../common
  blockchain_crypto:
    path: ../crypto
  blockchain_codecs:
    path: ../codecs
  blockchain_consensus:
    path: ../consensus
dev_dependencies:    
  build_runner: ^2.3.3
  test: ^1.24.0
  mockito: ^5.4.0
  convert: ^3.1.1
