name: blockchain_ledger
description: Blockchain ledger

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ">=2.17.0-266.8.beta <3.0.0"


dependencies:
  crypto: ^3.0.2
  bit_array:
  blockchain_protobuf:
    path: ../protobuf_dart
  blockchain_codecs:
    path: ../codecs
  blockchain_common:
    path: ../common

dev_dependencies:
  test: ^1.22.1
