name: blockchain_consensus
description: Blockchain Consensus

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.0.0


dependencies:
  fpdart: ^1.1.0
  rational: ^2.2.2
  hashlib: ^1.8.1
  logging:
  fixnum:
  blockchain_protobuf:
    path: ../protobuf_dart
  blockchain_codecs:
    path: ../codecs
  blockchain_common:
    path: ../common
  blockchain_crypto:
    path: ../crypto
dev_dependencies:    
  build_runner: ^2.3.3
  test:
  convert: ^3.1.1
