name: giraffe_sdk
description: Giraffe blockchain SDK

publish_to: 'none'

version: 1.0.5

environment:
  sdk: ^3.0.0

dependencies:
  async: ^2.11.0
  rxdart: ^0.28.0
  fixnum: ^1.1.0
  rational: ^2.2.3
  cryptography: ^2.7.0
  fast_base58: ^0.2.1
  hashlib: ^1.19.2
  logging: ^1.2.0
  fetch_client: ^1.0.2
  protobuf: ^3.1.0
dev_dependencies:    
  build_runner: ^2.4.11
  test: ^1.25.8
  mockito: ^5.4.4
