name: blockchain_sdk
description: Blockchain SDK

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  integral_isolates: ^0.5.1
  async: ^2.11.0
  rxdart: ^0.28.0
  fixnum: ^1.1.0
  fpdart: ^1.1.0
  rational: ^2.2.3
  cryptography: ^2.7.0
  fast_base58: ^0.2.1
  hashlib: ^1.19.2
  logging: ^1.2.0
  mockito: ^5.4.4
  grpc: ^4.0.0
  path: ^1.9.0
  hive: ^2.2.3
  quiver: ^3.2.1
  fetch_client: ^1.0.2
  blockchain_protobuf:
    path: ../protobuf_dart
dev_dependencies:    
  build_runner: ^2.4.11
  test: ^1.25.8
