name: blockchain_network
description: Blockchain network

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.0.0


dependencies:
  protobuf: ^3.1.0
  grpc: ^3.2.3
  fixnum: ^1.1.0
  async:
  logging:
  fast_base58:
  blockchain_crypto:
    path: ../crypto
  blockchain_protobuf:
    path: ../protobuf_dart

dev_dependencies:
  test: ^1.22.1
