name: blockchain
description: Blockchain

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.3.1
  integral_isolates: ^0.4.1
  async: ^2.11.0
  rxdart: ^0.27.7
  fixnum: ^1.1.0
  fpdart: ^1.1.0
  rational: ^2.2.2
  cryptography: ^2.7.0
  fast_base58: ^0.2.1
  hashlib: ^1.12.0
  logging: ^1.2.0
  mutex: ^3.1.0
  mockito: ^5.4.4
  grpc: ^3.2.4
  path: ^1.9.0
  blockchain_protobuf:
    path: ../protobuf_dart
dev_dependencies:    
  build_runner: ^2.4.7
  test: ^1.25.0
