name: blockchain
description: Blockchain

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.3.1
  integral_isolates: ^0.3.0+2
  async:
  rxdart:
  fixnum:
  fpdart:
  rational:
  cryptography:
  logging:
  blockchain_protobuf:
    path: ../protobuf_dart
  blockchain_minting:
    path: ../minting
  blockchain_consensus:
    path: ../consensus
  blockchain_common:
    path: ../common
  blockchain_codecs:
    path: ../codecs
  blockchain_ledger:
    path: ../ledger
  blockchain_crypto:
    path: ../crypto
  blockchain_wallet:
    path: ../wallet
  blockchain_network:
    path: ../network
dev_dependencies:    
  build_runner: ^2.3.3
