[package]
name = "rust_lib_giraffe_protocol"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.5.0"
giraffe_sdk = { path = "../../../rust/giraffe_sdk" }