name: blockchain_codecs
description: Blockchain codecs

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ">=2.17.0-266.8.beta <3.0.0"


dependencies:
  crypto: ^3.0.2
  bs58: ^1.0.2
  blockchain_protobuf:
    path: ../protobuf_dart

dev_dependencies:
  test: ^1.22.1
