name: blockchain_codecs
description: Blockchain Codecs

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'


dependencies:
  cryptography: ^2.0.5
  fpdart: ^0.3.0
  fast_base58: ^0.2.1
  blockchain_common:
    path: ../common
  blockchain_crypto:
    path: ../crypto
  blockchain_protobuf:
    path: ../protobuf_dart
dev_dependencies:    
  build_runner: ^2.3.3
