name: blockchain_common
description: Blockchain common

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ">=2.17.0-266.8.beta <3.0.0"


dependencies:
  fixnum:
  blockchain_protobuf:
    path: ../protobuf_dart

dev_dependencies:
  test: ^1.22.1
