name: blockchain_common
description: Blockchain common

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'


dependencies:
  fpdart: ^0.3.0
  fixnum:
  collection: ^1.17.2
  mutex: ^3.0.1
  blockchain_protobuf:
    path: ../protobuf_dart
  blockchain_crypto:
    path: ../crypto
dev_dependencies:    
  build_runner: ^2.3.3
  test:
  
