name: blockchain_wallet
description: Blockchain wallet

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0


dependencies:
  fixnum:
  fpdart:
  collection:
  blockchain_protobuf:
    path: ../protobuf_dart
  blockchain_common:
    path: ../common
  blockchain_crypto:
    path: ../crypto
  blockchain_codecs:
    path: ../codecs
  blockchain_ledger:
    path: ../ledger
dev_dependencies:    
  build_runner: ^2.3.3
  test: ^1.24.0
