name: blockchain_protobuf
description: Blockchain proto definitions

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ">=2.17.0-266.8.beta <3.0.0"


dependencies:
  protobuf: ^2.0.1
  grpc: ^3.0.2

dev_dependencies:
  test: ^1.22.1
