name: blockchain_protobuf
description: Blockchain proto definitions

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ">=3.0.0"


dependencies:
  protobuf: ^3.1.0
  grpc: ^4.0.0

dev_dependencies:
  test: ^1.25.8
