name: Build Dart

on:
  workflow_call:

jobs:
  build-dart:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
      
      - run: sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Verify Flutter Installation
        run: flutter doctor -v

      - name: Install flutter_to_debian
        run: dart pub global activate flutter_to_debian

      - name: Dart SDK Compile and Test
        working-directory: ./dart/sdk
        run: dart pub get && dart run build_runner build --delete-conflicting-outputs && dart test && dart test --platform chrome

      - name: Dart Node Compile and Test
        working-directory: ./dart/protocol
        run: dart pub get && dart run build_runner build --delete-conflicting-outputs && dart test

      - name: Frontend Compile and Test
        working-directory: ./dart/frontend
        run: flutter clean && flutter pub get && dart run build_runner build --delete-conflicting-outputs && flutter test && flutter test --platform chrome

      - name: Frontend Build CLI Staker
        working-directory: ./dart/protocol
        run: mkdir -p build/bin && dart compile exe bin/staker.dart -o build/bin/staker

      - name: Upload CLI Staker
        uses: actions/upload-artifact@v4
        with:
          name: cli-staker
          path: "dart/protocol/build/bin/staker"
          if-no-files-found: error

      - name: Frontend Build Web
        working-directory: ./dart/frontend
        run: flutter build web

      - name: Upload Web Frontend Dist
        uses: actions/upload-artifact@v4
        with:
          name: web-frontend-dist
          path: "dart/frontend/build/web"
          if-no-files-found: error
        
      - name: Frontend Build Android
        working-directory: ./dart/frontend
        run: flutter build apk --split-per-abi

      - name: Upload Android Frontend (arm64-v8a)
        uses: actions/upload-artifact@v4
        with:
          name: android-arm64-v8a-frontend-dist
          path: "dart/frontend/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk"
          if-no-files-found: error

      - name: Upload Android Frontend (armeabi-v7a)
        uses: actions/upload-artifact@v4
        with:
          name: android-armeabi-v7a-frontend-dist
          path: "dart/frontend/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk"
          if-no-files-found: error

      - name: Upload Android Frontend (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: android-x86_64-frontend-dist
          path: "dart/frontend/build/app/outputs/flutter-apk/app-x86_64-release.apk"
          if-no-files-found: error
        
      - name: Frontend Build Linux
        working-directory: ./dart/frontend
        run: flutter build linux --release && flutter_to_debian

      - name: Upload Linux Frontend
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb-frontend-dist
          path: "dart/frontend/build/linux/x64/release/debian/giraffe_*_amd64.deb"
          if-no-files-found: error
