name: Build TS

on:
  workflow_call:

jobs:
  build-ts:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: npm
          cache-dependency-path: typescript/sdk/package-lock.json
      - run: npm ci
        working-directory: ./typescript/sdk
      - name: TypeScript SDK Build and Test
        run: npm run test && npm run build
        working-directory: ./typescript/sdk
      - name: Upload TS SDK Dist
        uses: actions/upload-artifact@v4
        with:
          name: ts-sdk-dist
          path: "typescript/sdk/dist"
