name: Publish Docker Images

on:
  workflow_call:
    inputs:
      dev_tag:
        description: 'Publish a development tag.'
        default: false
        required: false
        type: boolean
      latest_tag:
        description: 'Publish a latest tag.'
        default: false
        required: false
        type: boolean

jobs:
  docker_publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scala
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push images to registries
        run: DOCKER_PUBLISH_DEV_TAG=${{ inputs.dev_tag }} DOCKER_PUBLISH_LATEST_TAG=${{ inputs.latest_tag }} sbt Docker/publish
