name: Publish Test Results

on:
  workflow_call:

jobs:
  publish-test-results:
    name: "Publish Tests Results"
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          name: sbt-test-results

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "artifacts/**/*.xml"
          check_name: "Test Results (${{ github.event.workflow_run.event || github.event_name }})"
