name: Pull Request

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    uses: ./.github/workflows/_build.yml
  publish-test-results:
    uses: ./.github/workflows/_publish_test_results.yml
    needs: [build]
    if: always()
